"""Audit event constants."""

USER_CREATED = "USER_CREATED"

USER_UPDATED = "USER_UPDATED"
PROFILE_UPDATED = "PROFILE_UPDATED"

PASSWORD_CHANGED = "PASSWORD_CHANGED"

USER_LOGIN = "USER_LOGIN"
USER_LOGOUT = "USER_LOGOUT"

USER_SOFT_DELETED = "USER_SOFT_DELETED"
USER_HARD_DELETED = "USER_HARD_DELETED"

PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"

PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"

ADMIN_PASSWORD_RESET_REQUESTED = (
    "ADMIN_PASSWORD_RESET_REQUESTED"
)