"""evolve user_sessions: add tracking fields, replace is_active with revoked_at

Revision ID: 8d6f7210ef75
Revises: 7c8516b54912
Create Date: 2026-08-09 09:16:24.476460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6f7210ef75'
down_revision: Union[str, Sequence[str], None] = '7c8516b54912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(length=400), nullable=True))
    op.add_column('user_sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_sessions', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'last_used_at')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'ip_address')
    # ### end Alembic commands ###
